package com.example.ibatis.mapper;

import com.example.ibatis.model.Config;
import org.springframework.stereotype.Repository;

import java.util.List;
@Repository
public interface ConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zs_gmuni_config
     *
     * @mbggenerated Thu Aug 02 11:00:55 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zs_gmuni_config
     *
     * @mbggenerated Thu Aug 02 11:00:55 CST 2018
     */
    int insert(Config record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zs_gmuni_config
     *
     * @mbggenerated Thu Aug 02 11:00:55 CST 2018
     */
    Config selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zs_gmuni_config
     *
     * @mbggenerated Thu Aug 02 11:00:55 CST 2018
     */
    List<Config> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zs_gmuni_config
     *
     * @mbggenerated Thu Aug 02 11:00:55 CST 2018
     */
    int updateByPrimaryKey(Config record);
}