package cn.gmuni.sysmenu.model;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Date;
@ApiModel(value = "系统资源（菜单）")
public class Resource {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_gmuni_resource.id
     *
     * @mbggenerated Mon May 28 11:00:22 CST 2018
     */
    @ApiModelProperty(value = "主键")
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_gmuni_resource.name
     *
     * @mbggenerated Mon May 28 11:00:22 CST 2018
     */
    @ApiModelProperty(value = "资源名称")
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_gmuni_resource.type
     *
     * @mbggenerated Mon May 28 11:00:22 CST 2018
     */
    @ApiModelProperty(value = "资源类型 0:目录 1:菜单 2:按钮")
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_gmuni_resource.url
     *
     * @mbggenerated Mon May 28 11:00:22 CST 2018
     */
    @ApiModelProperty(value = "如果是菜单，需要添加菜单路径")
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_gmuni_resource.button_code
     *
     * @mbggenerated Mon May 28 11:00:22 CST 2018
     */
    @ApiModelProperty(value = "如果是按钮，需要添加按钮编码")
    private String buttonCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_gmuni_resource.parent_id
     *
     * @mbggenerated Mon May 28 11:00:22 CST 2018
     */
    @ApiModelProperty(value = "资源父id")
    private String parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_gmuni_resource.code
     *
     * @mbggenerated Mon May 28 11:00:22 CST 2018
     */
    @ApiModelProperty(value = "资源编码，所有资源编码必须唯一")
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_gmuni_resource.parent_code
     *
     * @mbggenerated Mon May 28 11:00:22 CST 2018
     */
    @ApiModelProperty(value = "资源对应的父资源编码")
    private String parentCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_gmuni_resource.create_time
     *
     * @mbggenerated Mon May 28 11:00:22 CST 2018
     */
    @ApiModelProperty(value = "添加时间")
    private Date createTime;


    @ApiModelProperty(value = "状态0：禁用，1:启用")
    private String status;

    @ApiModelProperty(value = "排序号")
    private long sort;

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_gmuni_resource.id
     *
     * @return the value of pf_gmuni_resource.id
     *
     * @mbggenerated Mon May 28 11:00:22 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_gmuni_resource.id
     *
     * @param id the value for pf_gmuni_resource.id
     *
     * @mbggenerated Mon May 28 11:00:22 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_gmuni_resource.name
     *
     * @return the value of pf_gmuni_resource.name
     *
     * @mbggenerated Mon May 28 11:00:22 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_gmuni_resource.name
     *
     * @param name the value for pf_gmuni_resource.name
     *
     * @mbggenerated Mon May 28 11:00:22 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_gmuni_resource.type
     *
     * @return the value of pf_gmuni_resource.type
     *
     * @mbggenerated Mon May 28 11:00:22 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_gmuni_resource.type
     *
     * @param type the value for pf_gmuni_resource.type
     *
     * @mbggenerated Mon May 28 11:00:22 CST 2018
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_gmuni_resource.url
     *
     * @return the value of pf_gmuni_resource.url
     *
     * @mbggenerated Mon May 28 11:00:22 CST 2018
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_gmuni_resource.url
     *
     * @param url the value for pf_gmuni_resource.url
     *
     * @mbggenerated Mon May 28 11:00:22 CST 2018
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_gmuni_resource.button_code
     *
     * @return the value of pf_gmuni_resource.button_code
     *
     * @mbggenerated Mon May 28 11:00:22 CST 2018
     */
    public String getButtonCode() {
        return buttonCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_gmuni_resource.button_code
     *
     * @param buttonCode the value for pf_gmuni_resource.button_code
     *
     * @mbggenerated Mon May 28 11:00:22 CST 2018
     */
    public void setButtonCode(String buttonCode) {
        this.buttonCode = buttonCode == null ? null : buttonCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_gmuni_resource.parent_id
     *
     * @return the value of pf_gmuni_resource.parent_id
     *
     * @mbggenerated Mon May 28 11:00:22 CST 2018
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_gmuni_resource.parent_id
     *
     * @param parentId the value for pf_gmuni_resource.parent_id
     *
     * @mbggenerated Mon May 28 11:00:22 CST 2018
     */
    public void setParentId(String parentId) {
        this.parentId = parentId == null ? null : parentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_gmuni_resource.code
     *
     * @return the value of pf_gmuni_resource.code
     *
     * @mbggenerated Mon May 28 11:00:22 CST 2018
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_gmuni_resource.code
     *
     * @param code the value for pf_gmuni_resource.code
     *
     * @mbggenerated Mon May 28 11:00:22 CST 2018
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_gmuni_resource.parent_code
     *
     * @return the value of pf_gmuni_resource.parent_code
     *
     * @mbggenerated Mon May 28 11:00:22 CST 2018
     */
    public String getParentCode() {
        return parentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_gmuni_resource.parent_code
     *
     * @param parentCode the value for pf_gmuni_resource.parent_code
     *
     * @mbggenerated Mon May 28 11:00:22 CST 2018
     */
    public void setParentCode(String parentCode) {
        this.parentCode = parentCode == null ? null : parentCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_gmuni_resource.create_time
     *
     * @return the value of pf_gmuni_resource.create_time
     *
     * @mbggenerated Mon May 28 11:00:22 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_gmuni_resource.create_time
     *
     * @param createTime the value for pf_gmuni_resource.create_time
     *
     * @mbggenerated Mon May 28 11:00:22 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public long getSort() {
        return sort;
    }

    public void setSort(long sort) {
        this.sort = sort;
    }
}