package cn.gmuni.org.mapper;

import cn.gmuni.org.model.Department;
import cn.gmuni.org.model.DeptPart;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Service;

import java.util.List;
import java.util.Map;

@Service
public interface DepartmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_gmuni_department
     *
     * @mbg.generated Mon May 14 14:36:47 CST 2018
     */
    int deleteByPrimaryKey(String id);
    int deleteByIdsIn(List<String> ids);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_gmuni_department
     *
     * @mbg.generated Mon May 14 14:36:47 CST 2018
     */
    int insert(Department record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_gmuni_department
     *
     * @mbg.generated Mon May 14 14:36:47 CST 2018
     */
    Department selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_gmuni_department
     *
     * @mbg.generated Mon May 14 14:36:47 CST 2018
     */
    List<Department> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_gmuni_department
     *
     * @mbg.generated Mon May 14 14:36:47 CST 2018
     */
    int updateByPrimaryKey(Department record);
    Department getByName(@Param("name") String name);
    Department getByCode(@Param("code") String code);

    Department selectByNameAndDlevelCodeLike(@Param("name")String name, @Param("dlevelCode")String dlevelCode);
    int updateStatus(@Param("id") String id, @Param("status") String status);
    List<Department> selectByPid(Map<String, Object> para);
    int updateParent(@Param("id")String id, @Param("parentId")String parentId, @Param("dlevelCode")String dlevelCode, @Param("dlevel")long dlevel);
    int updateNameSimpleName(Department record);
    String getMaxDlevelCodeByPid(@Param("pid")String pid);

    long countByPid(Map<String, Object> para);

    long countByPids(List<String> pids);
    long countUserByPids(List<String> pids);

    /**
     * 登录查询权限专用
     * @param code
     * @return
     */
    List<String> getDlevelCodeByUserCode(String code);

    int addDeptParts(List<DeptPart> list);

    int delDeptPartsByDeptIds(List<String> deptIds);
    int delDeptPartsByUserIds(List<String> userIds);

    List<Department> listPartDeptByUserId(String userId);
}