package cn.gmuni.org.mapper;

import cn.gmuni.org.model.User;
import cn.gmuni.org.model.UserInfo;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Service;

import java.util.List;
import java.util.Map;

@Service
public interface UserInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_gmuni_userinfo
     *
     * @mbg.generated Mon May 14 14:36:47 CST 2018
     */
    int deleteByPrimaryKey(String id);
    int deleteByIdsIn(List<String> ids);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_gmuni_userinfo
     *
     * @mbg.generated Mon May 14 14:36:47 CST 2018
     */
    int insert(UserInfo record);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_gmuni_userinfo
     *
     * @mbg.generated Mon May 14 14:36:47 CST 2018
     */
    UserInfo selectByPrimaryKey(String id);
    UserInfo login(String code);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_gmuni_userinfo
     *
     * @mbg.generated Mon May 14 14:36:47 CST 2018
     */
    List<UserInfo> selectAll(Map<String, Object> queryPara);
    List<UserInfo> selectAllPageByDeptId(Map<String, Object> queryPara);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_gmuni_userinfo
     *
     * @mbg.generated Mon May 14 14:36:47 CST 2018
     */
    int updateByPrimaryKey(UserInfo record);
    int initializePwd(@Param("list")List<String> ids, @Param("pwd")String pwd);
    int changeState(@Param("list")List<String> ids, @Param("state")String state);

    List<UserInfo> listUserForAuthorize(String roleId);

    int checkOldPwd(@Param("code") String code, @Param("pwd") String oldPwd);

    int changePwd(@Param("code") String code,@Param("pwd") String pwd);

    int updateUserName(User user);
}