package cn.gmuni.enrollment.guide.model;

import java.util.Date;

public class EnrollmentPlan {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zs_gmuni_enrollment_plan.id
     *
     * @mbggenerated Thu Jun 07 11:58:35 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zs_gmuni_enrollment_plan.fap_id
     *
     * @mbggenerated Thu Jun 07 11:58:35 CST 2018
     */
    private String fapId;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zs_gmuni_enrollment_plan.enrolment
     *
     * @mbggenerated Thu Jun 07 11:58:35 CST 2018
     */
    private Integer enrolment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zs_gmuni_enrollment_plan.actual_enrollment
     *
     * @mbggenerated Thu Jun 07 11:58:35 CST 2018
     */
    private Integer actualEnrollment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zs_gmuni_enrollment_plan.provinces
     *
     * @mbggenerated Thu Jun 07 11:58:35 CST 2018
     */
    private String provinces;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zs_gmuni_enrollment_plan.create_time
     *
     * @mbggenerated Thu Jun 07 11:58:35 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zs_gmuni_enrollment_plan.year
     *
     * @mbggenerated Thu Jun 07 11:58:35 CST 2018
     */
    private String year;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zs_gmuni_enrollment_plan.edu_systme
     *
     * @mbggenerated Thu Jun 07 11:58:35 CST 2018
     */
    private Short eduSystme;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zs_gmuni_enrollment_plan.cost
     *
     * @mbggenerated Thu Jun 07 11:58:35 CST 2018
     */
    private Long cost;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zs_gmuni_enrollment_plan.id
     *
     * @return the value of zs_gmuni_enrollment_plan.id
     *
     * @mbggenerated Thu Jun 07 11:58:35 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zs_gmuni_enrollment_plan.id
     *
     * @param id the value for zs_gmuni_enrollment_plan.id
     *
     * @mbggenerated Thu Jun 07 11:58:35 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zs_gmuni_enrollment_plan.fap_id
     *
     * @return the value of zs_gmuni_enrollment_plan.fap_id
     *
     * @mbggenerated Thu Jun 07 11:58:35 CST 2018
     */
    public String getFapId() {
        return fapId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zs_gmuni_enrollment_plan.fap_id
     *
     * @param fapId the value for zs_gmuni_enrollment_plan.fap_id
     *
     * @mbggenerated Thu Jun 07 11:58:35 CST 2018
     */
    public void setFapId(String fapId) {
        this.fapId = fapId == null ? null : fapId.trim();
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zs_gmuni_enrollment_plan.enrolment
     *
     * @return the value of zs_gmuni_enrollment_plan.enrolment
     *
     * @mbggenerated Thu Jun 07 11:58:35 CST 2018
     */
    public Integer getEnrolment() {
        return enrolment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zs_gmuni_enrollment_plan.enrolment
     *
     * @param enrolment the value for zs_gmuni_enrollment_plan.enrolment
     *
     * @mbggenerated Thu Jun 07 11:58:35 CST 2018
     */
    public void setEnrolment(Integer enrolment) {
        this.enrolment = enrolment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zs_gmuni_enrollment_plan.actual_enrollment
     *
     * @return the value of zs_gmuni_enrollment_plan.actual_enrollment
     *
     * @mbggenerated Thu Jun 07 11:58:35 CST 2018
     */
    public Integer getActualEnrollment() {
        return actualEnrollment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zs_gmuni_enrollment_plan.actual_enrollment
     *
     * @param actualEnrollment the value for zs_gmuni_enrollment_plan.actual_enrollment
     *
     * @mbggenerated Thu Jun 07 11:58:35 CST 2018
     */
    public void setActualEnrollment(Integer actualEnrollment) {
        this.actualEnrollment = actualEnrollment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zs_gmuni_enrollment_plan.provinces
     *
     * @return the value of zs_gmuni_enrollment_plan.provinces
     *
     * @mbggenerated Thu Jun 07 11:58:35 CST 2018
     */
    public String getProvinces() {
        return provinces;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zs_gmuni_enrollment_plan.provinces
     *
     * @param provinces the value for zs_gmuni_enrollment_plan.provinces
     *
     * @mbggenerated Thu Jun 07 11:58:35 CST 2018
     */
    public void setProvinces(String provinces) {
        this.provinces = provinces == null ? null : provinces.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zs_gmuni_enrollment_plan.create_time
     *
     * @return the value of zs_gmuni_enrollment_plan.create_time
     *
     * @mbggenerated Thu Jun 07 11:58:35 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zs_gmuni_enrollment_plan.create_time
     *
     * @param createTime the value for zs_gmuni_enrollment_plan.create_time
     *
     * @mbggenerated Thu Jun 07 11:58:35 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zs_gmuni_enrollment_plan.year
     *
     * @return the value of zs_gmuni_enrollment_plan.year
     *
     * @mbggenerated Thu Jun 07 11:58:35 CST 2018
     */
    public String getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zs_gmuni_enrollment_plan.year
     *
     * @param year the value for zs_gmuni_enrollment_plan.year
     *
     * @mbggenerated Thu Jun 07 11:58:35 CST 2018
     */
    public void setYear(String year) {
        this.year = year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zs_gmuni_enrollment_plan.edu_systme
     *
     * @return the value of zs_gmuni_enrollment_plan.edu_systme
     *
     * @mbggenerated Thu Jun 07 11:58:35 CST 2018

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zs_gmuni_enrollment_plan.edu_systme
     *
     * @param eduSystme the value for zs_gmuni_enrollment_plan.edu_systme
     *
     * @mbggenerated Thu Jun 07 11:58:35 CST 2018
     */
    public void setEduSystme(Short eduSystme) {
        this.eduSystme = eduSystme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zs_gmuni_enrollment_plan.cost
     *
     * @return the value of zs_gmuni_enrollment_plan.cost
     *
     * @mbggenerated Thu Jun 07 11:58:35 CST 2018
     */
    public Long getCost() {
        return cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zs_gmuni_enrollment_plan.cost
     *
     * @param cost the value for zs_gmuni_enrollment_plan.cost
     *
     * @mbggenerated Thu Jun 07 11:58:35 CST 2018
     */
    public void setCost(Long cost) {
        this.cost = cost;
    }
}