package cn.gmuni.sysmenu.mapper;

import cn.gmuni.sysmenu.model.Resource;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Service;

import java.util.List;
import java.util.Map;

@Service
public interface ResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_gmuni_resource
     *
     * @mbggenerated Mon May 28 11:00:22 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_gmuni_resource
     *
     * @mbggenerated Mon May 28 11:00:22 CST 2018
     */
    int insert(Resource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_gmuni_resource
     *
     * @mbggenerated Mon May 28 11:00:22 CST 2018
     */
    Resource selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_gmuni_resource
     *
     * @mbggenerated Mon May 28 11:00:22 CST 2018
     */
    List<Resource> selectAll();
    List<Resource> selectAllWithoutButton();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_gmuni_resource
     *
     * @mbggenerated Mon May 28 11:00:22 CST 2018
     */
    int updateByPrimaryKey(Resource record);

    long countByPid(Map<String, Object> para);

    List<Resource> selectByPid(Map<String, Object> para);

    long countByPids(List<String> pids);

    int deleteByIdsIn(List<String> ids);

    int updateStatus(@Param("list")List<String> ids, @Param("status")String status);
    Resource selectByUrl(Resource resource);
    Resource selectByName(Resource resource);
    Resource selectByButtonCode(Resource resource);
}