package com.example.ibatis.model;

public class Config {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zs_gmuni_config.id
     *
     * @mbggenerated Thu Aug 02 11:00:55 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zs_gmuni_config.code
     *
     * @mbggenerated Thu Aug 02 11:00:55 CST 2018
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zs_gmuni_config.name
     *
     * @mbggenerated Thu Aug 02 11:00:55 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zs_gmuni_config.value
     *
     * @mbggenerated Thu Aug 02 11:00:55 CST 2018
     */
    private String value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zs_gmuni_config.sort
     *
     * @mbggenerated Thu Aug 02 11:00:55 CST 2018
     */
    private Long sort;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zs_gmuni_config.id
     *
     * @return the value of zs_gmuni_config.id
     *
     * @mbggenerated Thu Aug 02 11:00:55 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zs_gmuni_config.id
     *
     * @param id the value for zs_gmuni_config.id
     *
     * @mbggenerated Thu Aug 02 11:00:55 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zs_gmuni_config.code
     *
     * @return the value of zs_gmuni_config.code
     *
     * @mbggenerated Thu Aug 02 11:00:55 CST 2018
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zs_gmuni_config.code
     *
     * @param code the value for zs_gmuni_config.code
     *
     * @mbggenerated Thu Aug 02 11:00:55 CST 2018
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zs_gmuni_config.name
     *
     * @return the value of zs_gmuni_config.name
     *
     * @mbggenerated Thu Aug 02 11:00:55 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zs_gmuni_config.name
     *
     * @param name the value for zs_gmuni_config.name
     *
     * @mbggenerated Thu Aug 02 11:00:55 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zs_gmuni_config.value
     *
     * @return the value of zs_gmuni_config.value
     *
     * @mbggenerated Thu Aug 02 11:00:55 CST 2018
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zs_gmuni_config.value
     *
     * @param value the value for zs_gmuni_config.value
     *
     * @mbggenerated Thu Aug 02 11:00:55 CST 2018
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zs_gmuni_config.sort
     *
     * @return the value of zs_gmuni_config.sort
     *
     * @mbggenerated Thu Aug 02 11:00:55 CST 2018
     */
    public Long getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zs_gmuni_config.sort
     *
     * @param sort the value for zs_gmuni_config.sort
     *
     * @mbggenerated Thu Aug 02 11:00:55 CST 2018
     */
    public void setSort(Long sort) {
        this.sort = sort;
    }
}