package cn.gmuni.org.model;

import org.springframework.data.annotation.Transient;

import java.util.Date;
import java.util.List;

public class Department {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_gmuni_department.ID
     *
     * @mbg.generated Mon May 14 14:36:47 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_gmuni_department.name
     *
     * @mbg.generated Mon May 14 14:36:47 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_gmuni_department.simple_name
     *
     * @mbg.generated Mon May 14 14:36:47 CST 2018
     */
    private String simpleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_gmuni_department.code
     *
     * @mbg.generated Mon May 14 14:36:47 CST 2018
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_gmuni_department.parent_id
     *
     * @mbg.generated Mon May 14 14:36:47 CST 2018
     */
    private String parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_gmuni_department.type
     *
     * @mbg.generated Mon May 14 14:36:47 CST 2018
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_gmuni_department.remark
     *
     * @mbg.generated Mon May 14 14:36:47 CST 2018
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_gmuni_department.create_time
     *
     * @mbg.generated Mon May 14 14:36:47 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_gmuni_department.status
     *
     * @mbg.generated Mon May 14 14:36:47 CST 2018
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_gmuni_department.dLevel
     *
     * @mbg.generated Mon May 14 14:36:47 CST 2018
     */
    private Long dlevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_gmuni_department.dLevel_code
     *
     * @mbg.generated Mon May 14 14:36:47 CST 2018
     */
    private String dlevelCode;
    private String faculty;
    private String sort;
    @Transient
    private List<String> partsUsers;

    public List<String> getPartsUsers() {
        return partsUsers;
    }

    public void setPartsUsers(List<String> partsUsers) {
        this.partsUsers = partsUsers;
    }

    public String getSort() {
        return sort;
    }

    public void setSort(String sort) {
        this.sort = sort;
    }

    public String getFaculty() {
        return faculty;
    }

    public void setFaculty(String faculty) {
        this.faculty = faculty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_gmuni_department.ID
     *
     * @return the value of pf_gmuni_department.ID
     * @mbg.generated Mon May 14 14:36:47 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_gmuni_department.ID
     *
     * @param id the value for pf_gmuni_department.ID
     * @mbg.generated Mon May 14 14:36:47 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_gmuni_department.name
     *
     * @return the value of pf_gmuni_department.name
     * @mbg.generated Mon May 14 14:36:47 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_gmuni_department.name
     *
     * @param name the value for pf_gmuni_department.name
     * @mbg.generated Mon May 14 14:36:47 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_gmuni_department.simple_name
     *
     * @return the value of pf_gmuni_department.simple_name
     * @mbg.generated Mon May 14 14:36:47 CST 2018
     */
    public String getSimpleName() {
        return simpleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_gmuni_department.simple_name
     *
     * @param simpleName the value for pf_gmuni_department.simple_name
     * @mbg.generated Mon May 14 14:36:47 CST 2018
     */
    public void setSimpleName(String simpleName) {
        this.simpleName = simpleName == null ? null : simpleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_gmuni_department.code
     *
     * @return the value of pf_gmuni_department.code
     * @mbg.generated Mon May 14 14:36:47 CST 2018
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_gmuni_department.code
     *
     * @param code the value for pf_gmuni_department.code
     * @mbg.generated Mon May 14 14:36:47 CST 2018
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_gmuni_department.parent_id
     *
     * @return the value of pf_gmuni_department.parent_id
     * @mbg.generated Mon May 14 14:36:47 CST 2018
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_gmuni_department.parent_id
     *
     * @param parentId the value for pf_gmuni_department.parent_id
     * @mbg.generated Mon May 14 14:36:47 CST 2018
     */
    public void setParentId(String parentId) {
        this.parentId = parentId == null ? null : parentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_gmuni_department.type
     *
     * @return the value of pf_gmuni_department.type
     * @mbg.generated Mon May 14 14:36:47 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_gmuni_department.type
     *
     * @param type the value for pf_gmuni_department.type
     * @mbg.generated Mon May 14 14:36:47 CST 2018
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_gmuni_department.remark
     *
     * @return the value of pf_gmuni_department.remark
     * @mbg.generated Mon May 14 14:36:47 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_gmuni_department.remark
     *
     * @param remark the value for pf_gmuni_department.remark
     * @mbg.generated Mon May 14 14:36:47 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_gmuni_department.create_time
     *
     * @return the value of pf_gmuni_department.create_time
     * @mbg.generated Mon May 14 14:36:47 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_gmuni_department.create_time
     *
     * @param createTime the value for pf_gmuni_department.create_time
     * @mbg.generated Mon May 14 14:36:47 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_gmuni_department.status
     *
     * @return the value of pf_gmuni_department.status
     * @mbg.generated Mon May 14 14:36:47 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_gmuni_department.status
     *
     * @param status the value for pf_gmuni_department.status
     * @mbg.generated Mon May 14 14:36:47 CST 2018
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_gmuni_department.dLevel
     *
     * @return the value of pf_gmuni_department.dLevel
     * @mbg.generated Mon May 14 14:36:47 CST 2018
     */
    public Long getDlevel() {
        return dlevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_gmuni_department.dLevel
     *
     * @param dlevel the value for pf_gmuni_department.dLevel
     * @mbg.generated Mon May 14 14:36:47 CST 2018
     */
    public void setDlevel(Long dlevel) {
        this.dlevel = dlevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_gmuni_department.dLevel_code
     *
     * @return the value of pf_gmuni_department.dLevel_code
     * @mbg.generated Mon May 14 14:36:47 CST 2018
     */
    public String getDlevelCode() {
        return dlevelCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_gmuni_department.dLevel_code
     *
     * @param dlevelCode the value for pf_gmuni_department.dLevel_code
     * @mbg.generated Mon May 14 14:36:47 CST 2018
     */
    public void setDlevelCode(String dlevelCode) {
        this.dlevelCode = dlevelCode == null ? null : dlevelCode.trim();
    }
}