package cn.gmuni.org.model;

import java.util.Date;

public class Role {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_gmuni_role.id
     *
     * @mbg.generated Mon May 14 14:36:47 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_gmuni_role.code
     *
     * @mbg.generated Mon May 14 14:36:47 CST 2018
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_gmuni_role.name
     *
     * @mbg.generated Mon May 14 14:36:47 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_gmuni_role.create_time
     *
     * @mbg.generated Mon May 14 14:36:47 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_gmuni_role.state
     *
     * @mbg.generated Mon May 14 14:36:47 CST 2018
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_gmuni_role.remark
     *
     * @mbg.generated Mon May 14 14:36:47 CST 2018
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_gmuni_role.id
     *
     * @return the value of pf_gmuni_role.id
     *
     * @mbg.generated Mon May 14 14:36:47 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_gmuni_role.id
     *
     * @param id the value for pf_gmuni_role.id
     *
     * @mbg.generated Mon May 14 14:36:47 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_gmuni_role.code
     *
     * @return the value of pf_gmuni_role.code
     *
     * @mbg.generated Mon May 14 14:36:47 CST 2018
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_gmuni_role.code
     *
     * @param code the value for pf_gmuni_role.code
     *
     * @mbg.generated Mon May 14 14:36:47 CST 2018
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_gmuni_role.name
     *
     * @return the value of pf_gmuni_role.name
     *
     * @mbg.generated Mon May 14 14:36:47 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_gmuni_role.name
     *
     * @param name the value for pf_gmuni_role.name
     *
     * @mbg.generated Mon May 14 14:36:47 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_gmuni_role.create_time
     *
     * @return the value of pf_gmuni_role.create_time
     *
     * @mbg.generated Mon May 14 14:36:47 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_gmuni_role.create_time
     *
     * @param createTime the value for pf_gmuni_role.create_time
     *
     * @mbg.generated Mon May 14 14:36:47 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_gmuni_role.state
     *
     * @return the value of pf_gmuni_role.state
     *
     * @mbg.generated Mon May 14 14:36:47 CST 2018
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_gmuni_role.state
     *
     * @param state the value for pf_gmuni_role.state
     *
     * @mbg.generated Mon May 14 14:36:47 CST 2018
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_gmuni_role.remark
     *
     * @return the value of pf_gmuni_role.remark
     *
     * @mbg.generated Mon May 14 14:36:47 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_gmuni_role.remark
     *
     * @param remark the value for pf_gmuni_role.remark
     *
     * @mbg.generated Mon May 14 14:36:47 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}