package cn.gmuni.org.model;

import org.springframework.data.annotation.Transient;

import java.util.Date;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_gmuni_user.ID
     *
     * @mbg.generated Mon May 14 14:36:47 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_gmuni_user.name
     *
     * @mbg.generated Mon May 14 14:36:47 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_gmuni_user.code
     *
     * @mbg.generated Mon May 14 14:36:47 CST 2018
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_gmuni_user.sex
     *
     * @mbg.generated Mon May 14 14:36:47 CST 2018
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_gmuni_user.birthday
     *
     * @mbg.generated Mon May 14 14:36:47 CST 2018
     */
//    @JsonFormat(pattern="yyyy-MM-dd",timezone = "GMT+8")
//    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_gmuni_user.mobile
     *
     * @mbg.generated Mon May 14 14:36:47 CST 2018
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_gmuni_user.weixin
     *
     * @mbg.generated Mon May 14 14:36:47 CST 2018
     */
    private String weixin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_gmuni_user.mail
     *
     * @mbg.generated Mon May 14 14:36:47 CST 2018
     */
    private String mail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_gmuni_user.dept_id
     *
     * @mbg.generated Mon May 14 14:36:47 CST 2018
     */
    private String deptId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_gmuni_user.remark
     *
     * @mbg.generated Mon May 14 14:36:47 CST 2018
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_gmuni_user.create_time
     *
     * @mbg.generated Mon May 14 14:36:47 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_gmuni_user.qq
     *
     * @mbg.generated Mon May 14 14:36:47 CST 2018
     */
    private String qq;
    @Transient
    private String deptName;

    public String getDeptName() {
        return deptName;
    }

    public void setDeptName(String deptName) {
        this.deptName = deptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_gmuni_user.ID
     *
     * @return the value of pf_gmuni_user.ID
     *
     * @mbg.generated Mon May 14 14:36:47 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_gmuni_user.ID
     *
     * @param id the value for pf_gmuni_user.ID
     *
     * @mbg.generated Mon May 14 14:36:47 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_gmuni_user.name
     *
     * @return the value of pf_gmuni_user.name
     *
     * @mbg.generated Mon May 14 14:36:47 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_gmuni_user.name
     *
     * @param name the value for pf_gmuni_user.name
     *
     * @mbg.generated Mon May 14 14:36:47 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_gmuni_user.code
     *
     * @return the value of pf_gmuni_user.code
     *
     * @mbg.generated Mon May 14 14:36:47 CST 2018
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_gmuni_user.code
     *
     * @param code the value for pf_gmuni_user.code
     *
     * @mbg.generated Mon May 14 14:36:47 CST 2018
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_gmuni_user.sex
     *
     * @return the value of pf_gmuni_user.sex
     *
     * @mbg.generated Mon May 14 14:36:47 CST 2018
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_gmuni_user.sex
     *
     * @param sex the value for pf_gmuni_user.sex
     *
     * @mbg.generated Mon May 14 14:36:47 CST 2018
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_gmuni_user.birthday
     *
     * @return the value of pf_gmuni_user.birthday
     *
     * @mbg.generated Mon May 14 14:36:47 CST 2018
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_gmuni_user.birthday
     *
     * @param birthday the value for pf_gmuni_user.birthday
     *
     * @mbg.generated Mon May 14 14:36:47 CST 2018
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_gmuni_user.mobile
     *
     * @return the value of pf_gmuni_user.mobile
     *
     * @mbg.generated Mon May 14 14:36:47 CST 2018
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_gmuni_user.mobile
     *
     * @param mobile the value for pf_gmuni_user.mobile
     *
     * @mbg.generated Mon May 14 14:36:47 CST 2018
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_gmuni_user.weixin
     *
     * @return the value of pf_gmuni_user.weixin
     *
     * @mbg.generated Mon May 14 14:36:47 CST 2018
     */
    public String getWeixin() {
        return weixin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_gmuni_user.weixin
     *
     * @param weixin the value for pf_gmuni_user.weixin
     *
     * @mbg.generated Mon May 14 14:36:47 CST 2018
     */
    public void setWeixin(String weixin) {
        this.weixin = weixin == null ? null : weixin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_gmuni_user.mail
     *
     * @return the value of pf_gmuni_user.mail
     *
     * @mbg.generated Mon May 14 14:36:47 CST 2018
     */
    public String getMail() {
        return mail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_gmuni_user.mail
     *
     * @param mail the value for pf_gmuni_user.mail
     *
     * @mbg.generated Mon May 14 14:36:47 CST 2018
     */
    public void setMail(String mail) {
        this.mail = mail == null ? null : mail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_gmuni_user.dept_id
     *
     * @return the value of pf_gmuni_user.dept_id
     *
     * @mbg.generated Mon May 14 14:36:47 CST 2018
     */
    public String getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_gmuni_user.dept_id
     *
     * @param deptId the value for pf_gmuni_user.dept_id
     *
     * @mbg.generated Mon May 14 14:36:47 CST 2018
     */
    public void setDeptId(String deptId) {
        this.deptId = deptId == null ? null : deptId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_gmuni_user.remark
     *
     * @return the value of pf_gmuni_user.remark
     *
     * @mbg.generated Mon May 14 14:36:47 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_gmuni_user.remark
     *
     * @param remark the value for pf_gmuni_user.remark
     *
     * @mbg.generated Mon May 14 14:36:47 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_gmuni_user.create_time
     *
     * @return the value of pf_gmuni_user.create_time
     *
     * @mbg.generated Mon May 14 14:36:47 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_gmuni_user.create_time
     *
     * @param createTime the value for pf_gmuni_user.create_time
     *
     * @mbg.generated Mon May 14 14:36:47 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_gmuni_user.qq
     *
     * @return the value of pf_gmuni_user.qq
     *
     * @mbg.generated Mon May 14 14:36:47 CST 2018
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_gmuni_user.qq
     *
     * @param qq the value for pf_gmuni_user.qq
     *
     * @mbg.generated Mon May 14 14:36:47 CST 2018
     */
    public void setQq(String qq) {
        this.qq = qq == null ? null : qq.trim();
    }
}