package cn.gmuni.org.model;

import org.springframework.data.annotation.Transient;

import java.util.Date;

public class UserInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_gmuni_userinfo.ID
     *
     * @mbg.generated Mon May 14 14:36:47 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_gmuni_userinfo.user_id
     *
     * @mbg.generated Mon May 14 14:36:47 CST 2018
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_gmuni_userinfo.password
     *
     * @mbg.generated Mon May 14 14:36:47 CST 2018
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_gmuni_userinfo.state
     *
     * @mbg.generated Mon May 14 14:36:47 CST 2018
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_gmuni_userinfo.code
     *
     * @mbg.generated Mon May 14 14:36:47 CST 2018
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_gmuni_userinfo.username
     *
     * @mbg.generated Mon May 14 14:36:47 CST 2018
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_gmuni_userinfo.create_time
     *
     * @mbg.generated Mon May 14 14:36:47 CST 2018
     */

    private Date createTime;


    @Transient
    private String deptId;

    @Transient
    private String deptName;



    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_gmuni_userinfo.ID
     *
     * @return the value of pf_gmuni_userinfo.ID
     *
     * @mbg.generated Mon May 14 14:36:47 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_gmuni_userinfo.ID
     *
     * @param id the value for pf_gmuni_userinfo.ID
     *
     * @mbg.generated Mon May 14 14:36:47 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_gmuni_userinfo.user_id
     *
     * @return the value of pf_gmuni_userinfo.user_id
     *
     * @mbg.generated Mon May 14 14:36:47 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_gmuni_userinfo.user_id
     *
     * @param userId the value for pf_gmuni_userinfo.user_id
     *
     * @mbg.generated Mon May 14 14:36:47 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_gmuni_userinfo.password
     *
     * @return the value of pf_gmuni_userinfo.password
     *
     * @mbg.generated Mon May 14 14:36:47 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_gmuni_userinfo.password
     *
     * @param password the value for pf_gmuni_userinfo.password
     *
     * @mbg.generated Mon May 14 14:36:47 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_gmuni_userinfo.state
     *
     * @return the value of pf_gmuni_userinfo.state
     *
     * @mbg.generated Mon May 14 14:36:47 CST 2018
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_gmuni_userinfo.state
     *
     * @param state the value for pf_gmuni_userinfo.state
     *
     * @mbg.generated Mon May 14 14:36:47 CST 2018
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_gmuni_userinfo.code
     *
     * @return the value of pf_gmuni_userinfo.code
     *
     * @mbg.generated Mon May 14 14:36:47 CST 2018
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_gmuni_userinfo.code
     *
     * @param code the value for pf_gmuni_userinfo.code
     *
     * @mbg.generated Mon May 14 14:36:47 CST 2018
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_gmuni_userinfo.username
     *
     * @return the value of pf_gmuni_userinfo.username
     *
     * @mbg.generated Mon May 14 14:36:47 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_gmuni_userinfo.username
     *
     * @param username the value for pf_gmuni_userinfo.username
     *
     * @mbg.generated Mon May 14 14:36:47 CST 2018
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_gmuni_userinfo.create_time
     *
     * @return the value of pf_gmuni_userinfo.create_time
     *
     * @mbg.generated Mon May 14 14:36:47 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_gmuni_userinfo.create_time
     *
     * @param createTime the value for pf_gmuni_userinfo.create_time
     *
     * @mbg.generated Mon May 14 14:36:47 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public String getDeptId() {
        return deptId;
    }

    public void setDeptId(String deptId) {
        this.deptId = deptId;
    }

    public String getDeptName() {
        return deptName;
    }

    public void setDeptName(String deptName) {
        this.deptName = deptName;
    }
}